CREATE TABLE CITY(
    CITYID VARCHAR(20),
    CULTURE NUMERIC(2,0),
    CLIMATE NUMERIC(2,0),
    COUNTRY VARCHAR(20),
    AVGPRICE NUMERIC(5,0)
);
ALTER TABLE CITY ADD PRIMARY KEY(CITYID);

CREATE TABLE CULTURE(
    CULTUREID NUMERIC(2,0),
    PRIMLANGUAGE VARCHAR(20),
    CUISINE VARCHAR(20),
    HISTORICALSITES NUMERIC(2,0)
);
ALTER TABLE CULTURE ADD PRIMARY KEY(CULTUREID);
ALTER TABLE CITY ADD FOREIGN KEY(CULTURE) REFERENCES CULTURE(CULTUREID);

CREATE TABLE HISTORICALSITES(
    SITESID NUMERIC(2,0),
    SITE1 VARCHAR(30),
    SITE2 VARCHAR(30),
    SITE3 VARCHAR(30)
);
ALTER TABLE HISTORICALSITES ADD PRIMARY KEY(SITESID);
ALTER TABLE CULTURE ADD FOREIGN KEY(HISTORICALSITES) REFERENCES HISTORICALSITES(SITESID);

CREATE TABLE CLIMATE(
    CLIMATEID NUMERIC(2,0),
    BESTMONTHS NUMERIC(2,0),
    AVGWTEMP NUMERIC(2,0),
    AVGSPTEMP NUMERIC(2,0),
    AVGSMTEMP NUMERIC(2,0),
    AVGFTEMP NUMERIC(2,0)
);
ALTER TABLE CLIMATE ADD PRIMARY KEY(CLIMATEID);
ALTER TABLE CITY ADD FOREIGN KEY(CLIMATE) REFERENCES CLIMATE(CLIMATEID);

CREATE TABLE BESTMONTHS(
    MONTHSID NUMERIC(2,0),
    MONTH1 VARCHAR(9),
    MONTH2 VARCHAR(9),
    MONTH3 VARCHAR(9)
);
ALTER TABLE BESTMONTHS ADD PRIMARY KEY(MONTHSID);
ALTER TABLE CLIMATE ADD FOREIGN KEY(BESTMONTHS) REFERENCES BESTMONTHS(MONTHSID);

CREATE TABLE CLIENT(
    CLIENTID VARCHAR(20),
    ISGROUP VARCHAR(1)
);
ALTER TABLE CLIENT ADD PRIMARY KEY(CLIENTID);

CREATE TABLE REVIEW(
    CITY VARCHAR(20),
    CLIENT VARCHAR(20),
    RATING NUMERIC(2,0)
);
ALTER TABLE REVIEW ADD PRIMARY KEY(CITY,CLIENT);
ALTER TABLE REVIEW ADD FOREIGN KEY(CITY) REFERENCES CITY(CITYID);
ALTER TABLE REVIEW ADD FOREIGN KEY(CLIENT) REFERENCES CLIENT(CLIENTID);

CREATE TABLE TOUR(
    TOURID VARCHAR(30),
    STARTDATE VARCHAR2(10),
    ENDDATE VARCHAR2(10),
    COST NUMERIC(5,0),
    ACTIVITIES NUMERIC(2,0)
);
ALTER TABLE TOUR ADD PRIMARY KEY(TOURID);

CREATE TABLE ACTIVITIES(
    ACTIVITIESID NUMERIC(2,0),
    ACTIVITY1 VARCHAR(30),
    ACTIVITY2 VARCHAR(30),
    ACTIVITY3 VARCHAR(30)
);
ALTER TABLE ACTIVITIES ADD PRIMARY KEY(ACTIVITIESID);
ALTER TABLE TOUR ADD FOREIGN KEY(ACTIVITIES) REFERENCES ACTIVITIES(ACTIVITIESID);

CREATE TABLE CITYTOURPACKAGE(
    CITY VARCHAR(20),
    TOUR VARCHAR(30)
);
ALTER TABLE CITYTOURPACKAGE ADD PRIMARY KEY(CITY,TOUR);
ALTER TABLE CITYTOURPACKAGE ADD FOREIGN KEY(CITY) REFERENCES CITY(CITYID);
ALTER TABLE CITYTOURPACKAGE ADD FOREIGN KEY(TOUR) REFERENCES TOUR(TOURID);